milestones:
- title: Sprint 0 - Foundation Ready
  state: open
  description: Monorepo, local stack, auth, planning, SSE hello
- title: Sprint 1 - Preview Vertical Slice
  state: open
  description: 30s preview end-to-end, UI workspace, local A/B
issues:
- title: S0.1 Monorepo scaffold with pnpm workspaces
  body: 'apps/web, apps/api, packages/types, packages/cli; TS strict; lint/prettier;
    commit hooks.


    **Acceptance Criteria**: CI passes; packages build; types shared

    **Epic**: E0 - Project Bootstrap & DevEx

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S0.2 Local docker stack (Postgres, Redis, MinIO)
  body: 'docker-compose with healthchecks, volumes; seed scripts.


    **Acceptance Criteria**: All services healthy; can connect from api

    **Epic**: E0 - Project Bootstrap & DevEx

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S0.3 CI pipeline (lint/type/build/tests) + staging deploy
  body: 'GitHub Actions or equivalent; main→staging workflow.


    **Acceptance Criteria**: Green pipeline on PR; staging URL deployed

    **Epic**: E0 - Project Bootstrap & DevEx

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S1.1 Magic-link auth & sessions
  body: 'Passwordless email login; JWT/session; console email for dev.


    **Acceptance Criteria**: Login link grants session; whoami returns user

    **Epic**: E1 - Auth & Accounts

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S1.2 Project CRUD + ownership
  body: 'Create/list/rename/delete projects; owner-only access.


    **Acceptance Criteria**: CRUD via API/UI; access control enforced

    **Epic**: E1 - Auth & Accounts

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S2.1 Analyzer stub (lyrics parse; reference analysis placeholder)
  body: 'Syllable counts, rhyme hints; structure tokens.


    **Acceptance Criteria**: Given lyrics, returns tokens/metrics

    **Epic**: E2 - Planner Pipeline & Data Model

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S2.2 Planner v0 (structure/BPM/key heuristics)
  body: 'Generate plan.json; suggest BPM/key from genre preset.


    **Acceptance Criteria**: plan.json saved; sections seeded

    **Epic**: E2 - Planner Pipeline & Data Model

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S2.3 Orchestrator plan endpoints (+aliases)
  body: 'POST /plan/song, /plan/arrangement, /plan/vocals; idempotency keys.


    **Acceptance Criteria**: 200 with planId/seed; duplicate key returns first response

    **Epic**: E2 - Planner Pipeline & Data Model

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S3.4 SSE job stream
  body: 'GET /jobs/:id/events; heartbeats; reconnect.


    **Acceptance Criteria**: Front-end receives stage/progress updates

    **Epic**: E3 - Preview Path

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: S3.1 Music Synth stub path
  body: 'Generate click/guide + loop bed stems; seed-stable.


    **Acceptance Criteria**: 30s stems emitted; deterministic per seed

    **Epic**: E3 - Preview Path

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S3.2 Voice Synth stub (syllable-aligned tones)
  body: 'Align to section timing; harmonies toggle hook.


    **Acceptance Criteria**: Syllable-aligned tones render; harmony on/off works

    **Epic**: E3 - Preview Path

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S3.3 Mix & Master v0
  body: 'Sum stems; LUFS clamp; true-peak ceiling.


    **Acceptance Criteria**: -14 LUFS ±1; -1.0 dBTP

    **Epic**: E3 - Preview Path

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S6.2 Export preview (WAV/MP3)
  body: 'Write master.wav + mp3; presigned GET.


    **Acceptance Criteria**: Downloadable from UI; metadata set

    **Epic**: E6 - Export Packaging

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S4.1 Song Workspace shell
  body: 'Lyrics panel, Structure grid, Artist/Genre sidebar.


    **Acceptance Criteria**: Can create plan and view sections

    **Epic**: E4 - Web Frontend & Local Preview

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S4.2 Local WebAudio mixer + A/B
  body: 'Client-side transport; per-track gain/mute; A/B compare.


    **Acceptance Criteria**: A/B works without re-render

    **Epic**: E4 - Web Frontend & Local Preview

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: S4.3 Section controls (lock/regen placeholders)
  body: 'Buttons + keyboard shortcuts; hook to SSE.


    **Acceptance Criteria**: R/L shortcuts work; SSE updates UI

    **Epic**: E4 - Web Frontend & Local Preview

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
- title: T0.1 Init repo, TS strict, lint/prettier, commit hooks
  body: 'Prettier, ESLint, Husky; tsconfig strict.


    **Acceptance Criteria**: Precommit runs; ts --noEmit passes

    **Epic**: E0 - Project Bootstrap & DevEx

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: T0.2 Docker compose with healthchecks
  body: 'PG, Redis, MinIO services + volumes


    **Acceptance Criteria**: docker compose up → healthy

    **Epic**: E0 - Project Bootstrap & DevEx

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: T2.1 DB migrations for users/projects/takes/sections/jobs
  body: 'Prisma schema + migrate


    **Acceptance Criteria**: Tables created; migration repeatable

    **Epic**: E2 - Planner Pipeline & Data Model

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: T3.2 SSE server with heartbeats
  body: 'Fastify SSE plugin; retry strategy


    **Acceptance Criteria**: Event stream stable >5min

    **Epic**: E3 - Preview Path

    **Sprint**: Sprint 0'
  labels:
  - mvp
  - sprint-0
  milestone: Sprint 0 - Foundation Ready
- title: T4.2 WebAudio graph builder
  body: 'Graph nodes; scheduler; transport


    **Acceptance Criteria**: Tracks mix locally without pops

    **Epic**: E4 - Web Frontend & Local Preview

    **Sprint**: Sprint 1'
  labels:
  - mvp
  - sprint-1
  milestone: Sprint 1 - Preview Vertical Slice
